# -*- coding: utf-8 -*-
"""Contact Book App by using dictionary concept

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YMv9lOOF3eHIujfQz5bl0tIAcgmfUKoZ
"""

contacts={}

def show_menu():
  print("\n-----Show Menu-------")
  print("1. Add Contacts")
  print("2. View Contacts")
  print("3. Search Contact")
  print("4. Edit Contact")
  print("5. Delete Contact")
  print("6. Exit")
def add_contacts():
  name = input("Enter contact name: ")
  phone = input("Enter contact phone: ")
  email = input("Enter contact email: ")
  contacts[name] = {"phone": phone, "email": email}
  print(f"Contact {name} added successfully!")
def view_contacts():
  print("\n-----View Contacts-------")
  if not contacts:
    print("No contacts found.")
  else:
    for name, details in contacts.items():
      print(f"Name: {name}, Phone: {details['phone']}, Email: {details['email']}")
def search_contact():
  name = input("Enter contact name to search: ")
  if name in contacts:
    details = contacts[name]
    print(f"Name: {name}, Phone: {details['phone']}, Email: {details['email']}")
  else:
    print(f"Contact {name} not found.")
def edit_contact():
  name = input("Enter contact name to edit: ")
  if name in contacts:
    phone = input("Enter new phone (press Enter to skip): ")
    email = input("Enter new email (press Enter to skip): ")
    if phone:
      contacts[name]["phone"] = phone
    if email:
      contacts[name]["email"] = email
    print(f"Contact {name} edited successfully!")
  else:
    print(f"Contact {name} not found.")
def delete_contact():
  name = input("Enter contact name to delete: ")
  if name in contacts:
    del contacts[name]
    print(f"Contact {name} deleted successfully!")
  else:
    print(f"Contact {name} not found.")
while True:
  show_menu()
  choice = input("Enter your choice (1-6): ")

  if choice == "1":
    add_contacts()
  elif choice == "2":
    view_contacts()
  elif choice == "3":
    search_contact()
  elif choice == "4":
    edit_contact()
  elif choice == "5":
    delete_contact()
  elif choice == "6":
    print("Thank you for using the Contact Book. Goodbye!")
    break
  else:
    print("Invalid choice. Please select a valid option (1-6).")