# -*- coding: utf-8 -*-
"""Countdown timer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bQjjKukj9SS0UFCvsK1tmfMuINUrP-VR
"""

import time

start = int(input("Enter the start number:"))
print("\n-----Coutdown Start---------")
while start > 0:
  print(start)
  time.sleep(2)
  start-=2
print("------Coutdown Over-----")