# -*- coding: utf-8 -*-
"""Daily Journal Logger by using file handling concept

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gtE4HCHZO4NXz1Hf1-poiS8uEcvN-bBp
"""

journal_file = 'daily_journal.txt'
def add_entry():
  entry = input("Enter Daily Journal Entry: ")
  with open(journal_file, 'a') as file:
    file.write(entry + '\n')
  print("Entry added successfully!")
def view_entries():
  try:
    with open(journal_file, 'r') as file:
      content = file.read()
      if content:
        print("\n-----Daily Journal Entries----\n")
        print(content)
      else:
        print("No entries found.")
  except FileNotFoundError:
    print("No file found")
def search_entries():
  keyword = input("Enter a keyword to search for: ")
  try:
    with open(journal_file, 'r') as file:
      content = file.readlines()
      found = False
      print("\n-----Search Results----\n")
      for line in content:
        if keyword in line:
          print(line.strip())
          found = True
      if not found:
        print("No matching entries found.")
  except FileNotFoundError:
    print("No file found")

def show_menu():
  print("\n--- Daily Journal Logger ---")
  print("1. Add a new entry")
  print("2. View all entries")
  print("3. Search entries by keyword")
  print("4. Exit")
while True:
  show_menu()
  choice = input("Enter your choice:")
  if choice == '1':
    add_entry()
  elif choice == '2':
    view_entries()
  elif choice == '3':
    search_entries()
  elif choice == '4':
    print("Exiting the program. Goodbye!")
    break
  else:
    print("Invalid choice. Please try again and enter a number between (1-4) ")