# -*- coding: utf-8 -*-
"""Ingredients Checker by using set

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G-rAR_Djslqi_QkUalEFWrxGtGVyq1Un
"""

recipe_ingredients = {"flour", "sugar", "butter", "eggs", "milk"}
user_input = input("Enter ingredients: ")
user_ingredients = set(user_input.split(","))
missing_ingredients = recipe_ingredients - user_ingredients
extra_ingredients = user_ingredients - recipe_ingredients
print("\n------Ingredient Check Results------")
if missing_ingredients:
  print(f"Missing Ingredients: {','.join(missing_ingredients)}")
else:
  print("All ingredients present!")
if extra_ingredients:
  print(f"Extra Ingredients: {','.join(extra_ingredients)}")
else:
  print("No extra ingredients.")