# -*- coding: utf-8 -*-
"""Math Quiz Game

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bQjjKukj9SS0UFCvsK1tmfMuINUrP-VR
"""

from ast import operator
import random
def generate_random_question():
  num1 = random.randint(1,10)
  num2 = random.randint(1,10)
  operator=random.choice(['+','-','*','/'])
  if operator == '+':
    answer = num1 + num2
  elif operator == '-':
    answer = num1 - num2
  elif operator == '*':
    answer = num1 * num2
  elif operator == '/':
    answer = num1 / num2
  return f"{num1} {operator} {num2}",answer
def main():
  print("Welcome to the Math Quiz!")
  print("\n------Answer These Questions-----")
  score=0
  round=5
  for i in range(round):
    question,answer=generate_random_question()
    print(f"Question {i+1}: {question}")
    user_answer=int(input("Your Answer:"))
    if user_answer == answer:
      print("Correct!")
      score+=1
    else:
      print("Not Correct!")
  print("-----Game Over-----")
  print(f"\nyour score is {score}/{round}")
  if score == round:
    print("Congratulations! You Answer all The Questions Correctly")
  elif score >= 3:
    print("You did well!")
  else:
    print("Better Luck Next Time")
main()