# -*- coding: utf-8 -*-
"""note taking app by using file handling concept

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G-rAR_Djslqi_QkUalEFWrxGtGVyq1Un
"""

file_name = "myNotes.txt"

def show_menu():
  print("\n--- Note-Taking App Menu ---")
  print("1. Add a new note")
  print("2. View all notes")
  print("3. Delete all notes")
  print("4. Exit")
def add_note():
  note = input("Enter your note: ")
  with open(file_name,"a") as file:
    file.write(note+"\n")
  print("Note added successfully!")
def view_notes():
  try:
    with open(file_name, "r") as file:
      content = file.read()
      if content:
        print("\n--- Your Notes ---")
        print(content)
      else:
        print("\nNo notes found.")
  except FileNotFoundError:
    print("No notes found.")
def delete_notes():
  confirm = input("Are you sure you want to delete all notes? (Yes/n): ")
  if confirm.lower() == "yes":
    with open(file_name, "w") as file:
      pass
    print("All notes have been deleted")
  else:
    print("Deletion cancelled")
while True:
  show_menu()
  choice = input("Enter your choice (1-4): ")

  if choice == "1":
    add_note()
  elif choice == "2":
    view_notes()
  elif choice == "3":
    delete_notes()
  elif choice == "4":
    print("Exiting Note-Taking App. Goodbye!")
    break
  else:
    print("Invalid choice. Please enter a number between 1 and 4.")