# -*- coding: utf-8 -*-
"""number guessing game

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bQjjKukj9SS0UFCvsK1tmfMuINUrP-VR
"""

import random

secret_number=random.randint(1,10)
attempts=3

print("I'm thinking of a number between 1 and 10")

while attempts>0:
  guess=int(input("take a number:"))
  if guess == secret_number:
    print("Congratulations! Correct Number")
    break
  elif guess < secret_number:
    print("Number is Low")
  else:
    print("Number is high!")
  attempts-=1
if attempts==0:
  print("Sorry! Wrong answer... and the answer is",secret_number)