# -*- coding: utf-8 -*-
"""Recipe Viewer App by using file handling method

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DYy-ALRyAR8b46hlYAdNvyjZwnXfho2h
"""

def load_recipe(file):
  try:
    with open("sample1.txt",'r') as file:
      content = file.read()
      recipes = content.split("\n\n")
      recipe_dictionary = {}
      for recipe in recipes:
        lines = recipe.split("\n")
        if len(lines) >=3:
          recipe_name = lines[0]
          ingredients = lines[1].replace('Ingredients:', '').strip()
          instructions = lines[2].replace('Instructions:','').strip()
    return recipe_dictionary
  except FileNotFoundError:
    print("File not found")
    return{}
def show_menu():
  print("\n--- Recipe Viewer Menu ---")
  print("1. View Recipe by Name")
  print("2. List All Recipes")
  print("3. Exit")
def view_recipe(recipes):
  name = input("Enter the recipe name: ")
  if name in recipes:
    print(f"\nRecipe Name: {name}")
    print(f"Ingredients: {recipes[name]['ingredients']}")
    print(f"Instructions: {recipes[name]['instructions']}")
  else:
    print("Recipe not found")
recipe_file = "sample1.txt"
recipes = load_recipe(recipe_file)
while True:
  show_menu()
  choice = input("Enter your choice: ")
  if choice == "1":
    view_recipe(recipes)
  elif choice == "2":
    print("\n--- All Recipes ---")
    for name in recipes:
      print(name)
  elif choice == "3":
    print("Exiting the program.")
    break
  else:
    print("Invalid Choice! Please Try Again")