# -*- coding: utf-8 -*-
"""Shopping List App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bQjjKukj9SS0UFCvsK1tmfMuINUrP-VR
"""

shopping_list = []
def show_menu():
  print("\n------Shopping List Menu-----")
  print("1. View Shopping List")
  print("2. Add Item to Shopping List")
  print("3. Remove Item from Shopping List")
  print("4. Clear List")
  print("5. Quit")
while True:
  show_menu()
  choice = input("Enter your choice: ")
  if choice == "1":
    print("-----Shopping List-----")
    if not shopping_list:
      print("Your shopping list is empty.")
    else:
      for index, item in enumerate(shopping_list):
        print(f"{index+1}. {item}")
  elif choice == "2":
    item = input("Enter item to add:")
    shopping_list.append(item)
    print(f"{item} has been added to the shopping list")
  elif choice == "3":
    item = input("Enter item to remove:")
    if item in shopping_list:
      shopping_list.remove(item)
      print(f"{item} has been removed from the shopping list")
    else:
      print(f"{item} is not in the shopping list")
  elif choice == "4":
    shopping_list.clear()
    print("The Shopping List has been cleared")
  elif choice == "5":
    print("Thank you for using the Shopping List App")
    break
  else:
    print("Invalid choice. Please try again.")