# -*- coding: utf-8 -*-
"""Student Grade Manager by using list comprehension concept

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G-rAR_Djslqi_QkUalEFWrxGtGVyq1Un
"""

student_scores = input("Enter student scores seperated by commas: ")
scores = [int(score) for score in student_scores.split(",")]
grades = [
    "A" if score >=90 else
    "B" if score >=80 else
    "C" if score >=70 else
    "D" if score >=60 else
    "F"
    for score in scores
]
passing_students = [score for score in scores if score >= 60]
failing_students = [score for score in scores if score < 60]
print("\n-----Student Grades-----")
for i, (score, grade) in enumerate(zip(scores, grades), start=1):
  print(f"Student {i}: Score = {score}, Grade = {grade}")
print("\n-----Passing and Failing Students-----")
print(f"Passing Students: {passing_students}")
print(f"Failing Students: {failing_students}")