# -*- coding: utf-8 -*-
"""Student file report generator by using CSV file

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gtE4HCHZO4NXz1Hf1-poiS8uEcvN-bBp
"""

import csv

def process_student_data(input_file, output_file):
  try:
    with open(input_file,'r') as infile:
      reader = csv.DictReader(infile)
      student_reports =[]
      for row in reader:
        name = row['Name']
        english = int(row['English'])
        math = int(row['Math'])
        science = int(row['Science'])
        average = round((math+science+english)/3,2)
        status = "Pass" if average>=60 else "Fail"

        student_reports.append({
            'Name':name,
            'Math':math,
            'Science':science,
            'English':english,
            'Average':average,
            'Status':status
        })
    with open(output_file,'w',newline='') as outfile:
      fieldnames = ['Name','Math','Science','English','Average','Status']
      writer = csv.DictWriter(outfile,fieldnames=fieldnames)
      writer.writeheader()
      writer.writerows(student_reports)
    print(f"Student report generated in {output_file} successfully!")
  except FileNotFoundError:
    print(f"Input file '{input_file}' not found.")
  except KeyError:
    print("Invalid column names in the input file.")
  except Exception as e:
    print(f"An error occurred: {e}")
input_file = 'student_data.csv'
output_file = 'student_report.csv'
process_student_data(input_file,output_file)

